# Dockerfile to package the OrderService into a container image
FROM ubuntu:18.04
RUN apt update 2>/dev/null && apt install --yes sqlite3 2>/dev/null
COPY orderservice /usr/local/bin/orderservice
ENTRYPOINT ["/usr/local/bin/orderservice"]
